spring:
  application:
    name: eureka-server
server:
  port: 8081

eureka:
  instance:
    hostname: peer1
  client:
    serviceUrl:
      defaultZone: http://peer2:8082/eureka/
    register-with-eureka: false
    fetch-registry: false
